module.exports = [
    {
        loanType: "R",
        propertyTypes: "T",
        cityName: "San Francisco",
        purchasePrice: "200000",
        downPayment: "20000",
        addressOne: "113 North Cowboy Drive",
        addressThree: "San Francisco, CA 94063",
        firstName: "Faye",
        lastName: "Valentine",
        email: "Faye@crazymail.com",
        overviewName: "Faye Valentine",
        overviewEmail: "Faye@crazymail.com",
        overviewLoanType: "Refinance",
        overviewPropertyType: "Town Home",
        overviewCity: "San Francisco",
        overviewLoanTypeProperty: "Primary Home",
        overviewFoundHome: "True",
        overviewAgent: "True",
        overviewHomePrice: "200000",
        overviewDownPayment: "20000",
        overviewCreditScore: "Excellent",
        overviewBankruptcy: "Has never been in bankruptcy",
        overviewAddressOne: "113 North Cowboy Drive",
        overviewAddressThree: "San Francisco, CA 94063"
    },
    {
        loanType: "R",
        propertyTypes: "T",
        cityName: "Boston",
        purchasePrice: "500000",
        downPayment: "50000",
        addressOne: "3000 South Bebop Way",
        addressThree: "Boston, MA 02101",
        firstName: "Spike",
        lastName: "Spiegel",
        email: "Spike@crazymail.com",  
        overviewName: "Spike Spiegel",
        overviewEmail: "Spike@crazymail.com",
        overviewLoanType: "Refinance",
        overviewPropertyType: "Town Home",
        overviewCity: "Boston",
        overviewLoanTypeProperty: "Primary Home",
        overviewFoundHome: "True",
        overviewAgent: "True",
        overviewHomePrice: "500000",
        overviewDownPayment: "50000",
        overviewCreditScore: "Excellent",
        overviewBankruptcy: "Has never been in bankruptcy",
        overviewAddressOne: "3000 South Bebop Way",
        overviewAddressThree: "Boston, MA 02101"
    }
]